# Generated by Django 4.2.7 on 2023-11-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_weather_alter_post_content_alter_post_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file_upload',
        ),
    ]
