# Generated by Django 4.2.7 on 2023-11-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_head_image'),
        ('post', '0005_auto_20231129_1555'),
    ]

    operations = [
    ]
