# Generated by Django 4.2.7 on 2023-12-01 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_id_alter_weather_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=60, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
