# Generated by Django 4.2.7 on 2023-12-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_post_updated_at_alter_post_content_and_more'),
        ('post', '0012_alter_post_created_at'),
    ]

    operations = [
    ]
