# Generated by Django 3.1.1 on 2023-11-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_alter_weather_id'),
        ('forecast', '0005_choice_voters'),
    ]

    operations = [
    ]
