# Generated by Django 4.2.7 on 2023-11-29 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_alter_weather_id'),
        ('forecast', '0005_choice_voters'),
    ]

    operations = [
    ]
