# Generated by Django 4.2.7 on 2023-11-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_alter_choice_id_alter_poll_id'),
        ('forecast', '0007_auto_20231129_1555'),
    ]

    operations = [
    ]
